# Generated by Django 4.1.3 on 2022-11-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='address',
            field=models.URLField(default='https://www.google.com/maps/'),
        ),
    ]
