# Generated by Django 4.1.3 on 2022-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_add_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_name',
        ),
        migrations.AddField(
            model_name='add',
            name='place_name',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
