# Generated by Django 4.1.3 on 2022-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_add_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='place_name',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
