# Generated by Django 4.1.3 on 2022-11-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_user_reservation_day_user_reservation_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reservation',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='user_reservation',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
